[package]
# TODO(1) fix `authors` and `name` if you didn't use `cargo-generate`
authors = ["Folkert <folkert@folkertdev.nl>"]
name = "nrf9160-rust-starter"
edition = "2021"
version = "0.1.0"

[dependencies]
cortex-m = "0.7.3"
cortex-m-rt = "0.7.0"
defmt = "0.3.0"
defmt-rtt = "0.3.0"
panic-probe = { version = "0.3.0", features = ["print-defmt"] }
nrf9160-hal = "0.15.0"
# nrfxlib= { git = "https://github.com/folkertdev/nrfxlib", rev = "a5672efcaeaf8f4485d755e086cb36c00f79ca78" }
tinyrlibc = { git = "https://github.com/diondokter/tinyrlibc.git", branch = "ncs-2.0.1" }
nrfxlib-sys = { path = "../../nrfxlib-sys" }
nrf-modem = { path = "../../nrf-modem", features = ["defmt"] }

# cargo build/run --release
[profile.release]
debug = true
lto = true

overflow-checks = false # <-

# uncomment this to switch from the crates.io version of defmt to its git version
# check app-template's README for instructions
# [patch.crates-io]
# defmt = { git = "https://github.com/knurling-rs/defmt", rev = "use defmt version reported by `probe-run --version`" }
# defmt-rtt = { git = "https://github.com/knurling-rs/defmt", rev = "use defmt version reported by `probe-run --version`" }
# defmt-test = { git = "https://github.com/knurling-rs/defmt", rev = "use defmt version reported by `probe-run --version`" }
# panic-probe = { git = "https://github.com/knurling-rs/defmt", rev = "use defmt version reported by `probe-run --version`" }
