[package]
name = "nrf9160-rust-starter"
edition = "2021"
version = "0.1.0"

[dependencies]
cortex-m = { version = "0.7.6", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.0"
defmt = "0.3.0"
defmt-rtt = "0.3.0"
panic-probe = { version = "0.3.0", features = ["print-defmt"] }
tinyrlibc = { git = "https://github.com/diondokter/tinyrlibc.git", branch = "ncs-2.0.1" }
nrf-modem = { path = "../nrf-modem", features = ["defmt"] }
embassy = { git = "https://github.com/embassy-rs/embassy.git", rev = "4dc8007", features = ["nightly", "defmt"] }
embassy-nrf = { git = "https://github.com/embassy-rs/embassy.git", rev = "4dc8007", features = ["nightly", "nrf9160-ns", "unstable-pac", "time-driver-rtc1", "defmt"] }
futures = { version = "0.3", default-features = false }
libm = "0.2.5"

[profile.release]
debug = true
lto = true
